version: '3'
services:
  db:
    image: postgres:15.4-alpine
    container_name: desafio-ink-postgres
    volumes:
      - postgres_data_desafio_ink:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: desafio-ink
      POSTGRES_USER: ink
      POSTGRES_PASSWORD: ink-6SpgJ5*!YnZY0glcIL
    ports:
      - "5432:5432"
  web:
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: desafio-ink-web
    environment:
      DB_HOST: db
      DB_NAME: desafio-ink
      DB_USERNAME: ink
      DB_PASSWORD: ink-6SpgJ5*!YnZY0glcIL
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data_desafio_ink: {}
networks:
  default:
    name: desafio-ink-network